version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/egg-recipe/
    overwrite: true
    file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstall.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/AfterInstall.sh
      timeout: 300
      runas: root